### PR TITLE
Add button to close assessment without submitting

### PR DESCRIPTION
**Pull request by c0derMo**
### Checklist
- [x] I tested *all* changes and their related features locally or with a test instance of Artemis.
- [x] I documented the Java code using JavaDoc style.
- [x] I documented the changes in the Documentation (/docs).

### Motivation and Context
Discussion from Matrix Chat, no functionality to close an assessment without submitting it.

### Description
This PR adds a button labeled "Close Assessment" to the main assessment tab, which closes the current assessment and deletes the project locally, same as "Submit" does, with the difference that it neither saves nor submits the assessment. The functionality has been taken largely taken from the "Submit" button. This allows tutors to temporarily close an assessment, to continue working on it again later.

### Steps for Testing
1. Start Assessment of any exercise
2. Press "Close Assessment"
3. Assessment can be reloaded using the backlog-combos

### CODE REVIEW

**Comment by dfuchss** [comment]
@c0derMo sounds good. I'll have a look at it asap.
Could you also update the screenshots of the grading tool in the documentation?

**Comment by dfuchss** [comment]
As far as I can see (based on the code :) ) the button has been added to the backlog section. I would prefer the global assessment section (submit, save, etc.)

**Comment by c0derMo** [comment]
Moving the button to the global assessment section also makes sense, just wasn't sure if starting a new row for just one button makes sense here.

I'll move the button & update the screenshot in a bit.

**Comment by dfuchss** [comment]
> Moving the button to the global assessment section also makes sense, just wasn't sure if starting a new row for just one button makes sense here.

Feel free to re-arrange the buttons as you like :)

**Comment by dfuchss** [comment]
I've restructured the view a bit. If this fits, I guess we can merge the PR :)

Nice work !

**Review by dfuchss — APPROVED** [review]

**Pull request merged**
