### PR TITLE
Possible solution to fix the CI executable signing issue for macOS

### PR DESCRIPTION
**Pull request by zoemartin01**
I got executable signing to work on the GitHub runner with a self signed certificate. This still throws a warning when opening the executable for the first time on macOS since it's not a developer certificate, but at least you can still open it and it's not just rejected as being completely broken like the old releases. It uses GitHub Repository Secrets to store the certificate encoded in base64. To set this up a macOS capable machine is needed to create the certificate capable of code signing.

### CODE REVIEW

**Comment by dfuchss** [comment]
Thanks a lot for the PR. I'll take a look at it next week.

**Comment by dfuchss** [comment]
I've adopted your PR for testing and started workflows on `macos-test`

Do you have any idea why this Build breaks: https://github.com/kit-sdq/programming-lecture-eclipse-artemis/runs/4152092364?check_suite_focus=true

I can't test it on my PC since I have not macos 

Maybe [this](https://github.com/kit-sdq/programming-lecture-eclipse-artemis/runs/4152170936?check_suite_focus=true) workflow will work but if not I would have no idea how to test it :)

If [this](https://github.com/kit-sdq/programming-lecture-eclipse-artemis/runs/4152170936?check_suite_focus=true) builds .. could you verify whether it is runnable on your mac?

**Comment by dfuchss** [comment]
Ah I have some idea .. 

Does `-s` in `/usr/bin/codesign -s "Zoe Martin" -fv Eclipse.app` refers to the name of the certificate?

**Comment by zoemartin01** [comment]
> Does `-s` in `/usr/bin/codesign -s "Zoe Martin" -fv Eclipse.app` refers to the name of the certificate?

Yes this does indeed refer to the code signing certificate's name. It needs to be changed to whatever your certificate is called. Sorry I forgot that.

And sure if a build passes I can test it.

**Comment by dfuchss** [comment]
Do you have any ideas here : https://github.com/kit-sdq/programming-lecture-eclipse-artemis/runs/4152299095?check_suite_focus=true ? (If you are logged in you should see details)

It seems to import the certificate correctly see [here](https://github.com/kit-sdq/programming-lecture-eclipse-artemis/runs/4152299095?check_suite_focus=true#step:7:17)  .. but then it fails. Do you have any idea how to fix it?

**Comment by zoemartin01** [comment]
Is the certificate you are using a self signed one or an official developer certificate?

Also the identity name can be finnicky from my own experience. In my testing I could also use the SHA1 Fingerprint in place of the identity name, maybe that helps. Otherwise `security find-identity -p codesigning` shows the successfully imported identities for codesigning, by SHA1, name. Maybe that can help debugging.

**Comment by dfuchss** [comment]
Thanks for the idea .. I'll try that .. it's just self signed .. I have no "official" certificate from apple :)

**Comment by dfuchss** [comment]
Ok ... what are the extensions you have used for the certificate .. I set it to "Digital Sign" but maybe it has to be created in another way :)

**Comment by zoemartin01** [comment]
My certificate has the following extensions:
```
X509v3 extensions:
      X509v3 Key Usage: critical
          Digital Signature
      X509v3 Extended Key Usage: critical
          Code Signing
```

**Comment by dfuchss** [comment]
Thanks a lot. I'll test it :)

**Comment by dfuchss** [comment]
Seems to work 🎉 

Could you check whether the code of https://github.com/kit-sdq/programming-lecture-eclipse-artemis/runs/4155725247?check_suite_focus=true is runnable at macos.

If so, you may merge [macos-test](https://github.com/kit-sdq/programming-lecture-eclipse-artemis/tree/macos-test) into your branch or update your pr that it's able to be merged ?

**Comment by dfuchss** [comment]
In a follow-up PR we may consider to speedup the build (macos-latest seem to be quite slower that ubuntu-latest) .. maybe only run signing on macos-latest ?

**Comment by zoemartin01** [comment]
Yeah it works! Tested on macOS 10.15.7 and 11.3. Tho I wonder why it is so much smaller than the other distributions (or the one I compiled).

The only unintuitive thing for users will be that on first open it will still say it can't be opened.
Gatekeeper blocking Eclipse

But with the signed distribution you can get around that by going to `System Preferences > Security & Privacy` and click `Open Anyway`. Some reference to this should probably be mentioned in the wiki for users not familiar with self signed executables on mac.

**Comment by dfuchss** [comment]
> Yeah it works! Tested on macOS 10.15.7 and 11.3.

Nice 🎉 

>  Some reference to this should probably be mentioned in the wiki for users not familiar with self signed executables on mac.

You are absolutely right. Would you like to open another PR for that. Since I have no Mac, it might be quite hard for me to write anything useful here :)

**Comment by dfuchss** [comment]
@zoemartin01 is this what you have mentioned in https://github.com/kit-sdq/programming-lecture-eclipse-artemis/pull/129#issuecomment-964609534 everything you have to do that it runs in MacOS ?

If so, I would use that in the Wiki section of this project

**Pull request merged**
