### PR TITLE
Add a dialog for deleting annotations

### LINKED ISSUE #302: `Grading,Autograder`: Provide quick way to delete annotations
### Is your feature request related to a problem?

_No response_

### Describe the solution you'd like

When grading with the autograder it regularly is necessary to delete an annotation.
Searching the specific annotation in the list of annotations is not really practical, therefore a new workflow should be implemented.
Not quite sure what would be the most intuitive way of doing it, probably pressing a specific key to delete the annotation (or opening a window like with `Alt+Enter` in case there are multiple annotations in a line.

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Feuermagier**
### Checklist
- [x] I tested *all* changes and their related features locally or with a test instance of Artemis.
- [x] I documented the Java code using JavaDoc style.
- [x] I documented the changes in the Documentation (/docs).

### Motivation and Context
Deleting annotations with the marker view is tedious. Closes #302.

### Description
Adds a new command (by default Ctrl+Alt+Enter) that opens a small window (similar to the "create annotation" window) which shows all annotations at the current line. Press Del to select the selected annotation or Esc to close the dialog.

**Important:** This PR includes the changes made in #313, so I'm going to close the other PR.

### Steps for Testing
Start an assessment, focus the editor, press Ctrl+Alt+Enter.

### CODE REVIEW

**Review by dfuchss — CHANGES_REQUESTED** [review]
Please add documentation to the feature :)

**Review by dfuchss — APPROVED** [review]
Code lgtm

@tsaglam maybe test the behavior on MacOS :)

**Comment by tsaglam** [comment]
> @tsaglam maybe test the behavior on MacOS :)

Seems to work, however, deleting an annotation also deletes some code in the editor where the annotation is marked.

**Comment by tsaglam** [comment]
> @tsaglam maybe test the behavior on MacOS :)

After the fix it seems to work, no issues on macOS.

**Pull request merged**
